name: intelliattend_smartboard
description: Offline-resilient, TOTP-based attendance engine for university classrooms.
version: 5.4.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management & UI
  provider: ^6.1.1
  google_fonts: ^8.1.0
  qr_flutter: ^4.1.0
  video_player: ^2.9.1
  
  # Networking
  dio: ^5.4.1
  
  # Core Logic & Cryptography
  crypto: ^3.0.3
  http: ^1.1.0
  uuid: ^4.3.3
  
  # Storage & Security
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0
  flutter_secure_storage: ^10.1.0
  shared_preferences: ^2.2.2
  
  # Firebase
  firebase_core: ^4.7.0
  cloud_firestore: ^6.3.0

  # Environment Variables
  flutter_dotenv: ^6.0.1
  
  # Window Management
  window_manager: ^0.5.1
  screen_retriever: ^0.2.0
  screen_brightness: ^2.1.7
  
  # Notifications
  flutter_local_notifications: ^21.0.0

  # Windows Registry (for Startup)
  win32_registry: ^2.1.0
  
  # Logging
  logger: ^2.0.2+1

  # Path & Files
  path_provider: ^2.1.2
  
  # Network & Device Telemetry
  connectivity_plus: ^7.1.1
  device_info_plus: ^12.4.0
  package_info_plus: ^9.0.1
  web_socket_channel: ^3.0.3
  firebase_auth: ^6.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  isar_generator: ^3.1.0
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/background.png

dependency_overrides:
  flutter_secure_storage_windows:
    path: local_plugins/flutter_secure_storage_windows
  flutter_local_notifications_windows:
    path: local_plugins/flutter_local_notifications_windows
