from fastapi import FastAPI, Header, HTTPException
from pydantic import BaseModel
from datetime import datetime, timezone
import secrets
import uvicorn

app = FastAPI()

# Phase 1 Provisioning (Dummy Database mapping Silicon Signatures to Lecture Halls)
DATABASE = {
    # 0b8593a968a6513e873a71d866193c2db02b0a6d987a742b37cf81fa21d8b5f9 is the Exact Hash generated by the Windows Test Script
    "0b8593a968a6513e873a71d866193c2db02b0a6d987a742b37cf81fa21d8b5f9": {
        "room_name": "Classroom 101",
        "faculty_id": "FAC_123",
        "roster_count": 45
    }
}

class InitiateRequest(BaseModel):
    otp: str

@app.post("/v1/board/session/initiate")
async def initiate_session(request: InitiateRequest, x_board_mac: str = Header(None)):
    print(f"[Python] Incoming Handshake Request. Hardware Hash: {x_board_mac}")
    
    if not x_board_mac:
        raise HTTPException(status_code=400, detail="Missing X-Board-MAC Silicon Signature")

    # Phase 2: Daily Verification (The Bouncer)
    # Does Python recognize this exact processor/motherboard hash in the DB?
    room_data = DATABASE.get(x_board_mac)
    
    if not room_data:
        print("[Python] REJECTED: Untrusted hardware attempting to spoof connection.")
        raise HTTPException(status_code=403, detail="Untrusted Hardware. Hash not registered or spoofed.")

    # The hardware matches! Generate the 32-byte Cryptographic Seed for offline QR generation.
    cryptographic_seed = secrets.token_hex(32)
    server_time_iso =  datetime.now(timezone.utc).isoformat()
    
    print(f"[Python] APPROVED: Recognized {room_data['room_name']}. Dispensing seed.")

    return {
        "status": "success",
        "data": {
            "session_id": f"SESS_{secrets.token_hex(4).upper()}",
            "session_secret": cryptographic_seed,
            "scheduled_end_time": "2026-03-27T16:00:00Z",
            "faculty_details": {"name": "Professor Rahul", "course": "CS101"},
            "roster_count": room_data["roster_count"],
            "server_time": server_time_iso  # Injected specifically for Flutter's RTT Skew Engine!
        }
    }

if __name__ == "__main__":
    print("[Python] Starting The Brain (IntelliAttend Authentication Server) on port 8000...")
    uvicorn.run(app, host="127.0.0.1", port=8000)
